/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yctech_ndktest_Ndk */

#ifndef _Included_com_yctech_ndktest_Ndk
#define _Included_com_yctech_ndktest_Ndk
#ifdef __cplusplus
extern "C" {
#endif
#undef com_yctech_ndktest_Ndk_MODE_PRIVATE
#define com_yctech_ndktest_Ndk_MODE_PRIVATE 0L
#undef com_yctech_ndktest_Ndk_MODE_WORLD_READABLE
#define com_yctech_ndktest_Ndk_MODE_WORLD_READABLE 1L
#undef com_yctech_ndktest_Ndk_MODE_WORLD_WRITEABLE
#define com_yctech_ndktest_Ndk_MODE_WORLD_WRITEABLE 2L
#undef com_yctech_ndktest_Ndk_MODE_APPEND
#define com_yctech_ndktest_Ndk_MODE_APPEND 32768L
#undef com_yctech_ndktest_Ndk_MODE_MULTI_PROCESS
#define com_yctech_ndktest_Ndk_MODE_MULTI_PROCESS 4L
#undef com_yctech_ndktest_Ndk_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_yctech_ndktest_Ndk_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_yctech_ndktest_Ndk_BIND_AUTO_CREATE
#define com_yctech_ndktest_Ndk_BIND_AUTO_CREATE 1L
#undef com_yctech_ndktest_Ndk_BIND_DEBUG_UNBIND
#define com_yctech_ndktest_Ndk_BIND_DEBUG_UNBIND 2L
#undef com_yctech_ndktest_Ndk_BIND_NOT_FOREGROUND
#define com_yctech_ndktest_Ndk_BIND_NOT_FOREGROUND 4L
#undef com_yctech_ndktest_Ndk_BIND_ABOVE_CLIENT
#define com_yctech_ndktest_Ndk_BIND_ABOVE_CLIENT 8L
#undef com_yctech_ndktest_Ndk_BIND_ALLOW_OOM_MANAGEMENT
#define com_yctech_ndktest_Ndk_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_yctech_ndktest_Ndk_BIND_WAIVE_PRIORITY
#define com_yctech_ndktest_Ndk_BIND_WAIVE_PRIORITY 32L
#undef com_yctech_ndktest_Ndk_BIND_IMPORTANT
#define com_yctech_ndktest_Ndk_BIND_IMPORTANT 64L
#undef com_yctech_ndktest_Ndk_BIND_ADJUST_WITH_ACTIVITY
#define com_yctech_ndktest_Ndk_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_yctech_ndktest_Ndk_CONTEXT_INCLUDE_CODE
#define com_yctech_ndktest_Ndk_CONTEXT_INCLUDE_CODE 1L
#undef com_yctech_ndktest_Ndk_CONTEXT_IGNORE_SECURITY
#define com_yctech_ndktest_Ndk_CONTEXT_IGNORE_SECURITY 2L
#undef com_yctech_ndktest_Ndk_CONTEXT_RESTRICTED
#define com_yctech_ndktest_Ndk_CONTEXT_RESTRICTED 4L
#undef com_yctech_ndktest_Ndk_RESULT_CANCELED
#define com_yctech_ndktest_Ndk_RESULT_CANCELED 0L
#undef com_yctech_ndktest_Ndk_RESULT_OK
#define com_yctech_ndktest_Ndk_RESULT_OK -1L
#undef com_yctech_ndktest_Ndk_RESULT_FIRST_USER
#define com_yctech_ndktest_Ndk_RESULT_FIRST_USER 1L
#undef com_yctech_ndktest_Ndk_DEFAULT_KEYS_DISABLE
#define com_yctech_ndktest_Ndk_DEFAULT_KEYS_DISABLE 0L
#undef com_yctech_ndktest_Ndk_DEFAULT_KEYS_DIALER
#define com_yctech_ndktest_Ndk_DEFAULT_KEYS_DIALER 1L
#undef com_yctech_ndktest_Ndk_DEFAULT_KEYS_SHORTCUT
#define com_yctech_ndktest_Ndk_DEFAULT_KEYS_SHORTCUT 2L
#undef com_yctech_ndktest_Ndk_DEFAULT_KEYS_SEARCH_LOCAL
#define com_yctech_ndktest_Ndk_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_yctech_ndktest_Ndk_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_yctech_ndktest_Ndk_DEFAULT_KEYS_SEARCH_GLOBAL 4L
/*
 * Class:     com_yctech_ndktest_Ndk
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yctech_ndktest_Ndk_getStringFromNative
  (JNIEnv *, jobject);

/*
 * Class:     com_yctech_ndktest_Ndk
 * Method:    getString_From_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_yctech_ndktest_Ndk_getString_1From_1c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
